build_arch	= i386
header_arch	= x86_64
asm_link	= x86
defconfig	= defconfig
flavours        = generic generic-pae virtual
build_image	= bzImage
kernel_file	= arch/$(build_arch)/boot/bzImage
install_file	= vmlinuz
loader		= grub
skipabi		= true
skipmodule	= true
do_libc_dev_package=false
do_tools	= false
do_doc_package	= false
do_source_package=false
