/*
 * Copyright (C) 2010, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: epivers.h.in,v 13.30 2009/05/13 20:12:23 Exp $
 *
*/

#ifndef _epivers_h_
#define _epivers_h_

#define	EPI_MAJOR_VERSION	5

#define	EPI_MINOR_VERSION	60

#define	EPI_RC_NUMBER		48

#define	EPI_INCREMENTAL_NUMBER	36

#define EPI_BUILD_NUMBER	2

#define	EPI_VERSION		5, 60, 48, 36

#define	EPI_VERSION_NUM		0x053c3024

#define EPI_VERSION_DEV		5.60.48

#define	EPI_VERSION_STR		"5.60.48.36 "

#endif 
