/*
 * pcicfg.h: PCI configuration constants and structures.
 *
 * Copyright (C) 2010, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: pcicfg.h,v 1.49.68.1 2009/12/07 20:06:51 Exp $
 */

#ifndef	_h_pcicfg_
#define	_h_pcicfg_

#define	PCI_BAR0_WIN		0x80	
#define PCI_BAR0_WINSZ		(16 * 1024)	
#endif	
