#
# Makefile for the Linux kernel Jolicloud supplied third-party device drivers.
#

obj-$(CONFIG_BROADCOM_4312)	+= broadcom/
obj-$(CONFIG_RTL8192CU)		+= rtl8192cu/

# This is a stupid trick to get kbuild to create jolicloud/built-in.o
obj- += foo.o
