#
# Makefile for the Linux kernel Jolicloud supplied third-party device drivers.
#

obj-$(CONFIG_BROADCOM_4312)	+= broadcom/

+# This is a stupid trick to get kbuild to create jolicloud/built-in.o
+obj- += foo.o
