#!/bin/bash

# Select NIC type
card=RTL8192se

case "$card" in
        "RTL8192u")
	  ifconfig wlan0 down;;
        "RTL8192su")
	  ifconfig wlan0 down;;
        "RTL8190p")
	  ifconfig wlan0 down;;
        "RTL8192e")
	  ifconfig wlan0 down;;
        "RTL8192se")
	  ifconfig wlan0 down;;
	 "RTL8191se_Mesh")
	  ifconfig mesh0 down;
	  ifconfig ra0 down;;
        "RTL8192ce")
	  ifconfig wlan0 down;;
	"RTL8192ce_Mesh")
	  ifconfig mesh0 down;
	  ifconfig ra0 down;;
        *)
        echo "Unknown NIC type"
	break;;
esac


SYSTEM=`uname -r|cut -d. -f1,2`

if [ $SYSTEM = 2.4 ]
then
#rmmod 
case "$card" in
        "RTL8192u")
        rmmod r8192_usb;;
        "RTL8192su")
        rmmod r8192s_usb;;
        "RTL8190p")
        rmmod r8190_pci;;
        "RTL8192e")
        rmmod r8192e_pci;;
        "RTL8192se")
	rmmod r8192se_pci;;
	"RTL8191se_Mesh")
	rmmod r8192se_pci_mesh;;
        "RTL8192ce")
	rmmod r8192ce_pci;;
	"RTL8192ce_Mesh")
	rmmod r8192ce_pci_mesh;;
	*)
		echo "Unknown NIC type";;
esac
#rmmod rtllib-rsl
#rmmod rtllib_crypt_ccmp-rsl
#rmmod rtllib_crypt_tkip-rsl
#rmmod rtllib_crypt_wep-rsl
#rmmod aes-rsl
#rmmod michael_mic-rsl
#rmmod crypto-rsl
#rmmod rtllib_crypt-rsl
else

#rmmod 
case "$card" in
        "RTL8192u")
        rmmod r8192_usb.ko;;
        "RTL8192su")
        rmmod r8192s_usb.ko;;
        "RTL8190p")
        rmmod r8190_pci.ko;;
        "RTL8192e")
        rmmod r8192e_pci.ko;;
        "RTL8192se")
        rmmod r8192se_pci.ko;;
	"RTL8191se_Mesh")
	rmmod r8192se_pci_mesh.ko;;
        "RTL8192ce")
        rmmod r8192ce_pci.ko;;
	"RTL8192ce_Mesh")
	rmmod r8192ce_pci_mesh.ko;;
        *)
        echo "Unknown NIC type"
	break;;
esac

#for CRDA
#KERNEL_VER=`uname -r|cut -d- -f1|cut -d. -f3`
#if [ $KERNEL_VER -gt 29 ]
#then
	#modprobe -r cfg80211
#fi

#rmmod rtllib-rsl.ko
#rmmod rtllib_crypt_ccmp-rsl.ko
#rmmod rtllib_crypt_tkip-rsl.ko
#rmmod rtllib_crypt_wep-rsl.ko
#rmmod rtllib_crypt-rsl.ko
fi

