/*
 * Copyright (C) 2010, Broadcom Corporation
 * All Rights Reserved.
 * 
 * THIS SOFTWARE IS OFFERED "AS IS", AND BROADCOM GRANTS NO WARRANTIES OF ANY
 * KIND, EXPRESS OR IMPLIED, BY STATUTE, COMMUNICATION OR OTHERWISE. BROADCOM
 * SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A SPECIFIC PURPOSE OR NONINFRINGEMENT CONCERNING THIS SOFTWARE.
 *
 * $Id: phy_version.h.in,v 1.2 2009/06/18 06:28:33 Exp $
 *
*/

#ifndef phy_version_h_
#define phy_version_h_

#define	PHY_MAJOR_VERSION		1

#define	PHY_MINOR_VERSION		52

#define	PHY_RC_NUMBER		14

#define	PHY_INCREMENTAL_NUMBER	0

#define	PHY_BUILD_NUMBER		0

#define	PHY_VERSION			1, 52, 14, 0

#define	PHY_VERSION_NUM		0x01340e00

#define	PHY_VERSION_STR		"1.52.14.0"

#endif 
